theme: jekyll-theme-cayman

title: "NeurIPS 2025 E2LM Competition: Early Training Evaluation of Language Models"

description: 

timezone: Asia/Dubai

navigation:
  Home: "index"
  Rules: "rules"
  Timeline: "dates"
  Prizes: "prizes"
  Starter Kit: "starter_kit"
  Evaluation Metric: "evaluations"
  Leaderboard: "leaderboard"
  Organizers: "organizers"
markdown: kramdown

kramdown:
  parse_span_html: true
  parse_block_html: true
  math_engine: katex

plugins:
  - jekyll-seo-tag
  - jekyll-spaceship

exclude: ["README.md", "Gemfile", "Gemfile.lock"]
